[package]
name = "Vault"
version = "0.0.0"

[addresses]dd
Vault = "_"
ff


[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }
